In [1]:
import numpy as np

In [9]:
arr = np.arange(10).reshape(5,2)

In [10]:
arr

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [11]:
arr.sum()

45

In [12]:
arr.sum(axis = 0)

array([20, 25])

In [13]:
arr.sum(axis = 1)

array([ 1,  5,  9, 13, 17])

In [39]:
arr = np.arange(10).reshape(5,2)

In [40]:
arr

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [41]:
arr.sum(axis = 0)

array([20, 25])

In [42]:
arr.sum(axis = 1)

array([ 1,  5,  9, 13, 17])